### ISSUE TITLE
Fix actions

### ISSUE THREAD

**Issue by Matocolotoe** [Matocolotoe/Skript-1.8#17]
This needs to be fixed.

![image](https://user-images.githubusercontent.com/42092549/102995309-0f6d7100-4521-11eb-822d-806ba14fe2e2.png)

**Comment by TPGamesNL** [comment]
Git doesn't work well with binary files, see https://github.com/Matocolotoe/Skript-1.8/commit/13fa3bcbcd17e107eef97b7cdbc9fe2595c814e0#diff-12277790711b9f7dc1eb1b40d025e36afe07269ea7fa5a5745dff1079facbc61. Try uploading them to GitHub via the website, not via Git.

**Comment by Romitou** [comment]
We had however tried to restore the files modified by this commit to their original state, but without success. I will try to look again.
