### ISSUE TITLE
Clicking items on GUI not working

### ISSUE THREAD

**Issue by kimoVoid** [Matocolotoe/Skript-1.8#18]
I'm trying to make a script with this line(s):
```
on inventory click:
	if name of event-inventory is "Quests":
		cancel event
		if name of clicked slot "Kill 5 Players":
```

However, Skript simply does not recognize items with names. If I try to make a debug message to see what's the name of the clicked slot, it only works with empty spaces in the GUI. No console errors either.

**Comment by Matocolotoe** [comment]
Are you sure the code is correct ? Should be `if name of clicked slot is "Kill 5 Players":` with `is`

**Comment by kimoVoid** [comment]
Yes, i guess that was just a recent mistake but i also tried debugging with `on inventory click: broadcast "debug"` and it only works on empty spaces

**Comment by Matocolotoe** [comment]
Can't reproduce the issue with the latest version of Skript-1.8 on a Spigot 1.8.8 server.
Are you using 2.5.3 ? What server software are you using ?

**Comment by kimoVoid** [comment]
Yes, I'm using the latest version with paper 1.8.8. Is this issue related to paper?

**Comment by Matocolotoe** [comment]
Don't know, but it _could_ be

**Comment by kimoVoid** [comment]
Do you recommend any spigot forks that are optimized for 1.8? i'm running a bedwars server and i need it to be as optimized as it can. But again, this is 1.8, not 1.16, so is paper really necessary?

**Comment by Matocolotoe** [comment]
I don't think so, Paper doesn't bring that much features in 1.8, and imo Spigot is not that bad for 1.8, I've never had big performance problems with it

**Comment by kimoVoid** [comment]
I'll see how it goes, do you have any discord server for support? it's easier to talk about these things on discord

**Comment by Matocolotoe** [comment]
https://discord.gg/yh3Z98m
