### ISSUE TITLE
nbt "Tags:" does not work as intended

### ISSUE THREAD

**Issue by kill05** [Matocolotoe/Skript-1.8#19]
Hi, i tried using

spawn armor stand 2 meters above event-block's location with nbt "{NoGravity:1b,Tags:[test]}"
broadcast "%tag ""Tags"" of nbt of last spawned entity%"

and it didn't broadcast the value.
I tried the same thing in 1.12 and it broadcasted test.

there are no errors in the console, nor on skript reload

**Comment by Matocolotoe** [comment]
Skript itself doesn't have such expressions, so this is caused by an add-on

**Comment by kill05** [comment]
After some more investigation i'm pretty sure it's not due to skript but to another plugin conflicting somehow.

**Comment by Matocolotoe** [comment]
What other plugins are you using ?

**Comment by kill05** [comment]
it's 70 plugins so it's a bit hard to tell, but if you mean skript addons i have skbee,  skuniversal and a faction plugin that hooks with skript for some stuff

**Comment by Matocolotoe** [comment]
Not caused by Skript anyway.
