### ISSUE TITLE
Still biome issues

### ISSUE THREAD

**Issue by doesprintfwork** [Matocolotoe/Skript-1.8#3]
The new alpha doesn't fix the issue for the biome.

**Comment by doesprintfwork** [comment]
https://imgur.com/a/Efxnduk

**Comment by Matocolotoe** [comment]
Yeah, didn't work on it yet. What's the code you used ?

**Comment by doesprintfwork** [comment]
literally just
```
loop all players:
    send "ur in biome %biome at location of loop-player%" to loop-player
```

**Comment by Matocolotoe** [comment]
And the biomes with empty names are the ones who changed name in the next versions ?

**Comment by doesprintfwork** [comment]
Yes I think so

**Comment by Matocolotoe** [comment]
Alright, will investigate on this

**Comment by Matocolotoe** [comment]
The issue will be fixed in the update. Thanks for reporting !
