### ISSUE TITLE
Add support for database (mysql)

### ISSUE THREAD

**Issue by dominikd1977** [Matocolotoe/Skript-1.8#31]
It would be really cool if the skript could connect to database. (mysql and other)
I know that there are addons for this but none of them is just working with this version. (I tried old and new version of skquery, same with skriptdb but nothing worked)

**Comment by Matocolotoe** [comment]
This fork only aims to make features compatible with 1.8, not to add some.
If you're having issues with Skript, report them here : https://github.com/SkriptLang/Skript

**Comment by MotikaCraft-TheJoshua** [comment]
This is now possible, you can test yourself and let know of any issues
PR: https://github.com/Matocolotoe/Skript-1.8/pull/96
Download: https://github.com/TheJoshue/Skript-1.8/actions/runs/11304703223 (Scroll below to find download button)
