### ISSUE TITLE
Problem of comparing ItemTypes

### ISSUE THREAD

**Issue by Romitou** [Matocolotoe/Skript-1.8#32]
For example, using the code below, the `ItemType#isTypeOf` method does not work as expected, with for example nether warts:
```applescript
on click on nether wart:
    broadcast "test"
```
Related code: https://github.com/Matocolotoe/Skript-1.8/blob/master/src/main/java/ch/njol/skript/events/EvtClick.java#L197
The ItemStack of `o` equals `ItemStack{NETHER_WARTS x 1}` while the ItemStack of `block` equals `ItemStack{NETHER_STALK x 1}`, which means that the event does not work.

**Comment by AyhamAl-Ali** [comment]
I think this might help https://github.com/SkriptLang/Skript/pull/4162 :+1:

**Comment by Matocolotoe** [comment]
The issue doesn't occur on 1.9+ with official Skript builds, with or without this pull request, so it's only related to 1.8 I guess.
