### ISSUE TITLE
Log handler not stopped correctly, not saving variables on shutdown

### ISSUE THREAD

**Issue by W0lfyZRex** [Matocolotoe/Skript-1.8#35]
Hello I got an error that happens when my server has been up for a couple hours and it makes it so I can't execute any Skript effect commands, and the worst part is that after this error happens, any variable that gets edited won't get saved at all so when the server restarts, it will roll the variables back.
![image](https://user-images.githubusercontent.com/66094336/120074960-9e1d8580-c09f-11eb-9ef1-209f8608f3ac.png)
I don't really know why that happens, something with parsing? Help me please :(

Skript 2.5.3
Spigot 1.8.8

**Comment by Matocolotoe** [comment]
Are you using skript-mirror ? If so, what version of it ?

**Comment by wlofly** [comment]
No I'm not.

**Comment by wlofly** [comment]
I was using skript-mirror but I removed it before the screenshot so it's not related (and it was skript-mirror 2.0)

**Comment by wlofly** [comment]
I don't even know what script causes this error that's pissing me off a lot

**Comment by Matocolotoe** [comment]
Please edit your messages instead of sending multiple ones.
I'll take a look at it, but I don't think it's related to Skript-1.8.

**Comment by wlofly** [comment]
Alright, thanks!

**Comment by wlofly** [comment]
Now I have another problem. For some reason, when the Skript plugin unloads when the server stops, it just makes the whole server freeze and I have to manually kill it or else it won't ever restart.
![image](https://user-images.githubusercontent.com/66094336/120118602-afe05500-c193-11eb-86b5-f03b172a7799.png)
Nothing happens after this line, I'm very confused.
Should I create another issue for that?

Also got that:
![image](https://user-images.githubusercontent.com/66094336/120120677-1cad1c80-c19f-11eb-8b6c-441f4a0d8c56.png)

**Comment by wlofly** [comment]
![image](https://user-images.githubusercontent.com/66094336/120327969-a4ec0880-c2ea-11eb-83f8-441898679a5b.png)
So that's a native Skript issue, but I can't get rid of it until you release a 2.6 1.8 version

**Comment by Matocolotoe** [comment]
Then it's not related to Skript-1.8.

**Comment by wlofly** [comment]
Well that's sad because half of the variables don't save (including things that could cost irl money) and I can't do anything about it until you release a working 2.6 retro-compatible Skript. It's weird that almsot no one gets this error, I don't get what I'm doing wrong with the "parsed as" effect. I don't even know why I'm using Skript, I could just try to learn Java lmfao

**Comment by Matocolotoe** [comment]
I currently don't have time for anything that requires more than 20 minutes :/
