### ISSUE TITLE
Problem with colored armor.

### ISSUE THREAD

**Issue by Molotouf** [Matocolotoe/Skript-1.8#37]
### Description
It is not possible to give a player coloured leather armour.

### Steps to Reproduce
In a command, I put a line to give a piece of leather armor colored in blue to the player.
Exemple:
```
command /test:
	trigger:
		give 1 leather helmet dyed blue to player
```

### Expected Behavior
Normally it should give me a blue leather helmet, but the player gets nothing.

### Errors / Screenshots
https://pastebin.com/601kKeNi

The server is on TacoSpigot 1.8.8
Skript 2.6-beta2

**Comment by Matocolotoe** [comment]
The error and the related expression both come from Skellett, therefore this is not related to Skript-1.8.
