### ISSUE TITLE
I can't cancel an on death event.

### ISSUE THREAD

**Issue by frandma** [Matocolotoe/Skript-1.8#39]
### Skript Version

[Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases
[Skript] Skript's documentation can be found here: https://skriptlang.github.io/Skript
[Skript] Server Version: git-PaperSpigot-"4c7641d" (MC: 1.8.8)
[Skript] Skript Version: 2.5.3
[Skript] Installed Skript Addons:
[Skript] - WolvSK v1.7.2

### Bug Description

When i try to cancel an on death event it says "An on death event cannot be cancelled (main.sk, line 195: cancel event')".

### Expected Behavior

It was supposed to cancel the on death event and not send the error message as it does on newer skript versions.

### Steps to Reproduce

I wrote
"
on death:
    cancel event
"
and it did not work.

### Errors or Screenshots

![image](https://user-images.githubusercontent.com/93941927/140797352-b2146c39-67c0-4fec-93bf-0b2e49a7b0fc.png)

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by Matocolotoe** [comment]
As the message says, a death event cannot be cancelled. It has only been implemented in recent versions of Paper.
https://github.com/PaperMC/Paper/blob/master/patches/server/0263-Improve-death-events.patch
