### ISSUE TITLE
is online condition is broken

### ISSUE THREAD

**Issue by zakwanasim** [Matocolotoe/Skript-1.8#40]
### Skript Version

2.5.3

### Bug Description

command /test:
    trigger:
        set {_player} to player
        {_player} is online:
            send "yes" to player
        else:
            send "no" to player

sends "no"

### Expected Behavior

no

### Steps to Reproduce

copy the code

### Errors or Screenshots

![image](https://user-images.githubusercontent.com/59154045/143323355-51cd3556-891d-42f3-9c4b-8886409e171e.png)

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment]
If you have Vixio remove it, Vixio has a type that conflicts with `is online` condition

**Comment by zakwanasim** [comment]
thanks
