### ISSUE TITLE
send title doesn't work

### ISSUE THREAD

**Issue by pawelkuwa** [Matocolotoe/Skript-1.8#42]
### Skript Version

```
Replace this text with your output from the command.
```

### Bug Description

skript doesn't read title effect

### Expected Behavior

send title

### Steps to Reproduce

i execute code from docs in skript docs 

### Errors or Screenshots

![image](https://user-images.githubusercontent.com/83598982/151529969-047e0f68-66d0-43dc-a6eb-ec464fe35c83.png)
![image](https://user-images.githubusercontent.com/83598982/151529928-c563489b-c635-43c3-ae0e-b7c0862c1186.png)

### Other

version of skript 
![image](https://user-images.githubusercontent.com/83598982/151529898-6874c407-d2ce-4353-a99c-c75c1eb29a6a.png)

### Agreement

- [x] I have read the guidelines above and confirm I am following them with this report.

**Comment by AyhamAl-Ali** [comment]
afaik, spigot 1.8[.8] doesn't support titles with duration, just titles [docs](https://shanebeestudios.com/docs/spigot/1.8.8/org/bukkit/entity/Player.html#sendTitle-java.lang.String-java.lang.String-)

**Comment by Matocolotoe** [comment]
Indeed, the API doesn't. However, I think the client can still receive a PacketPlayOutTitle with more parameters, as eyesniper2 did [here](https://github.com/eyesniper2/skRayFall/blob/master/src/main/java/net/rayfall/eyesniper2/skrayfall/v1_8_3/EffTitleV1_8_3.java) for skRayFall. I'll take a more precise look at it ASAP.

**Comment by AyhamAl-Ali** [comment]
That's a smart idea, good to know.
