### ISSUE TITLE
Colors during parsing won't work

### ISSUE THREAD

**Issue by wallace4BR** [Matocolotoe/Skript-1.8#46]
### Skript Version

Skript 2.6.1 since 2.6

### Bug Description

Title says all, color won't work while parsing scripts but it does work in other things

### Expected Behavior

Should be colored

### Steps to Reproduce

Reload an script that contains any error/warnings

### Errors or Screenshots

![image](https://user-images.githubusercontent.com/81590228/155040048-971244d5-8319-4c3a-b643-ae4c9975cd87.png)

But here it does have colors
![image](https://user-images.githubusercontent.com/81590228/155040132-e558f9b8-3f85-4467-8300-5e04b144460c.png)

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by Griffeng** [comment]
I cannot recreate this colors work fine in newest version.
![javaw_sLH8bqoDZO](https://user-images.githubusercontent.com/42309996/165551041-b67794dd-9fc7-4be6-9f4e-2c7e8146b9f6.png)

**Comment by wallace4BR** [comment]
> I cannot recreate this colors work fine in newest version. ![javaw_sLH8bqoDZO](https://user-images.githubusercontent.com/42309996/165551041-b67794dd-9fc7-4be6-9f4e-2c7e8146b9f6.png)

Not sure if the issue happens in the game tho
Maybe it's related to that issue?
[4728](https://github.com/SkriptLang/Skript/pull/4728)

**Comment by Matocolotoe** [comment]
Seems related to the Skript issue you mentioned indeed.
