### ISSUE TITLE
Getting this error

### ISSUE THREAD

**Issue by Drakunovu** [Matocolotoe/Skript-1.8#5]
Hello I use PaperMC in 1.8.8 and I'm getting this error with the latest release.

Edit: Removed some lines to make this thing more short
```
[00:23:48] [Server thread/INFO]: [Skript] Enabling Skript v2.5-alpha3
[00:23:49] [Server thread/INFO]: [Skript] You're currently running custom Skript version. No updates will be automatically installed.
[00:23:49] [Server thread/ERROR]: Error occurred while enabling Skript v2.5-alpha3 (Is it up to date?)
java.lang.StackOverflowError
	at java.util.regex.Pattern$CharProperty.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$Branch.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$GroupHead.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$Loop.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$GroupTail.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$BranchConn.match(Unknown Source) ~[?:1.8.0_241]
	at java.util.regex.Pattern$CharProperty.match(Unknown Source) ~[?:1.8.0_241]

After lots of this lines
[00:23:49] [Server thread/INFO]: [Skript] Disabling Skript v2.5-alpha3
```

**Comment by tbringuier** [comment]
Are you using SkQuery ?

**Comment by Matocolotoe** [comment]
Make sure you haven't used characters involved in Skript's parser such as `|` somewhere

**Comment by Walid-Korchi** [comment]
`java.lang.StackOverflowError`
what does it mean ??

**Comment by Matocolotoe** [comment]
https://docs.oracle.com/javase/7/docs/api/java/lang/StackOverflowError.html
Consider asking questions regarding Java somewhere else ^^

**Comment by Walid-Korchi** [comment]
okay oof, thank you

**Comment by Drakunovu** [comment]
> Are you using SkQuery ?

no

> Make sure you haven't used characters involved in Skript's parser such as `|` somewhere

Idk what means but it's clean installation

**Comment by tbringuier** [comment]
Can you give us the list of the plugins actually installed on your server ?
(Plugin + Skript Addons)

**Comment by Romitou** [comment]
This seems to be related to SkriptLang/Skript#2752.

**Comment by Drakunovu** [comment]
> This seems to be related to [SkriptLang/Skript#2752](https://github.com/SkriptLang/Skript/issues/2752).

Using OpenJDK Java 11 and still the same error.

> Can you give us the list of the plugins actually installed on your server ?
> (Plugin + Skript Addons)

AuthMe, Citizens, DeluxeMenus, AdvancedBan, NickNamer, LuckPerms, Skript, SkyWars, Vault, FAWE, GadgetsMenu, Ersatz, PlaceHolderAPI, ProtocolLib, PacketListenerAPI, and FastLogin

**Comment by tbringuier** [comment]
🤔

**Comment by Matocolotoe** [comment]
@Drakunovu Apparently my first sentence wasn't clear.
In your scripts, do you use characters such as `|` ?

**Comment by SnowPyon** [comment]
Skript doesn't support 1.8.8, so it shouldn't work either way.

**Comment by Matocolotoe** [comment]
This fork makes the plugin work in 1.8.x (only), that's why it's called "Skript-1.8".

**Comment by Drakunovu** [comment]
> @Drakunovu Apparently my first sentence wasn't clear.
> In your scripts, do you use characters such as `|` ?

Nope it's a clean installation no scripts

**Comment by Romitou** [comment]
Like I said on SkriptLang repo, i think i found part of the problem. Do you have Java in 32bits?
Can you send us a `java -version` screen of your console?

**Comment by Drakunovu** [comment]
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment AdaptOpenJDK <build 11.0.7+10>
OpenJDK Client VM AdaptOpenJDK <build 11.0.7+10, mixed mode>

Edit: And yes i'm 32 bits

**Comment by tbringuier** [comment]
It would be better tu use java 8 (openjdk-8-jdk) i think.

**Comment by Drakunovu** [comment]
> It would be better tu use java 8 (openjdk-8-jdk) i think.

I have installed that version and it's the same error

**Comment by Matocolotoe** [comment]
Doesn't seem related to Skript-1.8.
