### ISSUE TITLE
Damage cause projectile not working

### ISSUE THREAD

**Issue by Chopnex** [Matocolotoe/Skript-1.8#51]
### Skript Version

```
Replace this text with your output from the command.
```

There is nothing from the console

### Bug Description

When using the syntax for damage cause and check for a projectile in the on death event nothing is registered

It works with attack but not projectile.

### Expected Behavior

The syntax should work

### Steps to Reproduce

```
on death of player:
    if damage cause is projectile:
        send "Works"
```

### Errors or Screenshots

```
Replace this text with your paste link or errors/screenshots/videos.
```

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by Matocolotoe** [comment]
Likely the same as https://github.com/SkriptLang/Skript/issues/4709.
