### ISSUE TITLE
TuSKe broken commands

### ISSUE THREAD

**Issue by ghost** [Matocolotoe/Skript-1.8#52]
### Skript Version

![image](https://user-images.githubusercontent.com/72381315/162623343-188a6df1-e9cc-48f6-87a3-d9e5ae7b706e.png)

### Bug Description

My custom commands no longer work after installing TuSKe 
I didnt contact them becuse
It happend sometime with another addon too

### Expected Behavior

For /customitems to open a gui

### Steps to Reproduce

1. Install a skript addon
2. Try using any custom commands
3. See unknown command error

### Errors or Screenshots

![image](https://user-images.githubusercontent.com/72381315/162623401-a4fe2886-873c-4dff-8c04-6b107b01cbde.png)

This is a image of me running /customitems and it didnt work
Code: https://gist.github.com/ANDREI12333/230676c531e0b7f26127956e566fae55

### Other

No

### Agreement

- [x] I have read the guidelines above and confirm I am following them with this report.

**Comment by Matocolotoe** [comment]
This is a repository dedicated to Skript-1.8, not addons.
Also, TuSKe is no longer maintained. You could try using the latest PikachuPatch available here : https://skripttools.net/addons?q=tuske

**Comment by ghost** [comment]
@Matocolotoe It happens with multiple addons

**Comment by Matocolotoe** [comment]
Either they don't support 1.8 or they don't work with Skript 2.6+, but that's out of the scope of this plugin anyway. You could try contacting their author or using alternatives such as skript-reflect.
