### ISSUE TITLE
SkLimeQuery 1.8 doesn't work

### ISSUE THREAD

**Issue by ghost** [Matocolotoe/Skript-1.8#56]
### Skript Version

![image](https://user-images.githubusercontent.com/72381315/165513758-f55e8c56-7ac1-4115-ae85-fb9967c035da.png)

### Bug Description

Skript doesn't load my .sk files anymore after adding SkLimeQuery 1.8

### Expected Behavior

For skript to load my .sk files and not get a error in console

### Steps to Reproduce

1. Installed, SkQueryLime for 1.8 from the 1.8 skript repository
2. Restarted the server
3. See error

### Errors or Screenshots

**Skript Info:**
![image](https://user-images.githubusercontent.com/72381315/165513921-01e0b782-b6c7-473e-b918-2d82e3482f60.png)
[Error](https://gist.github.com/ANDREI12333/02a59fde386364fa99bf42d23f3e7d1c)

### Agreement

- [x] I have read the guidelines above and confirm I am following them with this report.

**Comment by Griffeng** [comment]
1.8,8 uses skQuery 3.21.4 this one https://dev.bukkit.org/projects/skquery/files/816515

**Comment by ghost** [comment]
@Griffeng Excuse me, I'm using a skQuery patch for 1.8.8 that is provided in THIS repository.

**Comment by ghost** [comment]
@Griffeng 
![image](https://user-images.githubusercontent.com/72381315/165547741-a556997e-3bf8-443f-bdec-19276b4b959c.png)

**Comment by Matocolotoe** [comment]
SkQuery v4.1.1 does *not* work with Skript 2.6+.
I will update the addon section ASAP.
For now, you can use [SkQuery v4.1.6 edited for 1.8](https://cdn.discordapp.com/attachments/697442955555897394/955521182789152798/SkQuery-4.1.6.jar), it is the one available on Discord.

**Comment by ghost** [comment]
Issue solved by @Matocolotoe:
![image](https://user-images.githubusercontent.com/72381315/165817672-900555ac-1929-461c-8108-55d845812a41.png)

**Comment by ghost** [comment]
@Matocolotoe Btw i have this problem with multiple addons like skungee isn't working...

**Comment by Matocolotoe** [comment]
> @Matocolotoe Btw i have this problem with multiple addons like skungee isn't working...

Try using a more suitable version for 1.8, or contact the addon author. I provided a patched version of SkQuery because this addon is popular, and other frequently used ones do work.

**Comment by ghost** [comment]
@Matocolotoe Okay!
