### ISSUE TITLE
Plugin doesn't enable

### ISSUE THREAD

**Issue by ghost** [Matocolotoe/Skript-1.8#57]
### Skript Version

I'm unable to do this.

### Bug Description

Skript enables then disables its self

### Expected Behavior

For skript to run

### Steps to Reproduce

1. Start server
2. See error

### Errors or Screenshots

**Error: (Using pterodactyl)**
![image](https://user-images.githubusercontent.com/72381315/166731434-43021b6d-1104-457a-9bc8-bd7d23126dac.png)

**Error Paste:** 
https://gist.github.com/ANDREI12333/607da5acf6428a80f3299505dc32f106

### Other

**DEBUG:**
Server Version:  1.8.8
Skript Version:  2.6.1
Software: PaperMC

### Agreement

- [x] I have read the guidelines above and confirm I am following them with this report.

**Comment by Matocolotoe** [comment]
Try deleting your materials.json file and let Skript regenerate it.

**Comment by ghost** [comment]
@Matocolotoe Thank you, The materials.json file contained 1.18.2 content while the server was made for 1.8.8, Becuse i forgot to change the server's version before installing skript.
