### ISSUE TITLE
Issue with armor change condition

### ISSUE THREAD

**Issue by LeCoqbBeau** [Matocolotoe/Skript-1.8#58]
### Skript Version

![info](https://user-images.githubusercontent.com/65740503/172026964-20b992cc-1aba-43a4-ba55-08bd4102cb19.png)

### Bug Description

The event "on armor change:" doesnt work at all. It gave an error all the time saying the plugin doesnt recognize the event
![Capture d’écran 2022-06-05 001052](https://user-images.githubusercontent.com/65740503/172027000-1a39b44a-bf3a-45af-ac49-4e402469c984.png)
.

### Expected Behavior

Expected behavior is that the plugin actually understand the event armor change and actually output anything after this condition.

### Steps to Reproduce

To reproduce this bug is just to go on any skript file and put those lines : 
```
on armor change:
    send "You equipped %event-item%!"
```
And the plugin will say that it doesnt understand something at all here.

### Agreement

- [x] I have read the guidelines above and confirm I am following them with this report.

**Comment by DampfWaffel** [comment]
i think this is not a problem of this fork. because the event was not added back in 1.8.8

**Comment by Matocolotoe** [comment]
This event requires Paper 1.12+.
