### ISSUE TITLE
cant use Tablist expr

### ISSUE THREAD

**Issue by DampfWaffel** [Matocolotoe/Skript-1.8#59]
### Skript Version

```
2.6.1 and 2.5.3 this fork
```

### Bug Description

The use of this expression trigger the unknown effect/expression error.

https://skripthub.net/docs/?id=3738

### Expected Behavior

the tablist should be changed

### Steps to Reproduce

set all players' tab list header to "Welcome to the Server!"

### Errors or Screenshots

```
Replace this text with your paste link or errors/screenshots/videos.
```

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by Matocolotoe** [comment]
This expression requires Minecraft 1.13+.
