### ISSUE TITLE
on drop kill event-entity kills player instead of dropped item

### ISSUE THREAD

**Issue by c0dingnoobi** [Matocolotoe/Skript-1.8#65]
### Skript Version

```Skript's aliases can
be found here: https://github.com/SkriptLang/skript-aliases
Skript's documentation can be found here: https://skriptlang.github.io/Skript
Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials
Server Version: git-Titanium-JENKINS-dev-117 (MC: 1.8.8)
Skript Version: 2.6.4-for-1.8
Installed Skript Addons: 
  - skript-placeholders v1.5.2 (https://github.com/APickledWalrus/skript-placeholders)
  - skript-gui v1.3 (https://github.com/APickledWalrus/skript-gui)
  - skript-yaml v1.4
  - skDragon v0.17
  - skript-reflect v2.3 (https://github.com/TPGamesNL/skript-reflect)
  - SkBee v1.10.3 (https://github.com/ShaneBeee/SkBee)
Installed dependencies: 
  - Vault v1.7.3-b${env.TRAVIS_BUILD_NUMBER}
  - WorldGuard v6.2.1;84bc322
```

### Bug Description

Since 319142448c2a79b25c757306947f6e61bec27593 killing the event-entity inside of the on drop event kills the player who was involved in the event instead of the dropped item (which used to work on 2.6.2)

### Expected Behavior

Killing the dropped item instead of killing the player

### Steps to Reproduce

```
on drop:
  kill event-entity
```

### Errors or Screenshots

None available

### Other

Nothing to add ig

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by Idani1** [comment]
This is expected behavior in skript. Have you tried using event-item or event-itementity instead?

**Comment by NotSoDelayed** [comment]
Use `kill event-item entity`
