### ISSUE TITLE
on form event does not exist

### ISSUE THREAD

**Issue by NopeProsOnly** [Matocolotoe/Skript-1.8#68]
### Skript Version

```
[11:42:36 INFO]: [Skript] Skript's aliases can be found here: https://github.com/SkriptLang/skript-aliases

[11:42:36 INFO]: [Skript] Skript's documentation can be found here: https://docs.skriptlang.org/

[11:42:36 INFO]: [Skript] Skript's tutorials can be found here: https://docs.skriptlang.org/tutorials

[11:42:36 INFO]: [Skript] Server Version: git-Spigot-21fe707-741a1bd (MC: 1.8.8)

[11:42:36 INFO]: [Skript] Skript Version: 2.6.4-for-1.8

[11:42:36 INFO]: [Skript] Installed Skript Addons: None

[11:42:36 INFO]: [Skript] Installed dependencies:

[11:42:36 INFO]: [Skript]  - WorldGuard v6.1.3-SNAPSHOT;c904242
```

### Bug Description

```
on form:
  cancel event
```
This does not stop cobblestone generators. Infact, I don't think the event even exists. How else do I stop generators?

### Expected Behavior

It was supposed to cancel the event and stop the cobblestone from forming.

### Steps to Reproduce

```
on form:
  cancel event
```

Make a generator, and boom.

### Errors or Screenshots

```
No errors
```
https://www.xbox.com/en-US/play/media/2A6JBT5M9X

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by Matocolotoe** [comment]
BlockFormEvent doesn't trigger when cobblestone is created by a generator

**Comment by NopeProsOnly** [comment]
I'm pretty sure it does. 
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/block/BlockFormEvent.html
![image](https://user-images.githubusercontent.com/78925970/223784523-b74f46ec-692e-48e1-96bb-e16b185d5e40.png)

**Comment by Matocolotoe** [comment]
I've tested it on a 1.8.8 server and it doesn't :
```java
public void onForm(BlockFormEvent e) {
    Bukkit.broadcastMessage("form");
}
```

The exemples you've mentioned are only relevant for the latest Spigot version. Only the following are written in the 1.8 documentation :

![image](https://user-images.githubusercontent.com/42092549/223788965-9fbdd906-36bd-4327-a838-afbd5db829d0.png)

**Comment by Matocolotoe** [comment]
If you want to disable cobblestone generators, you might be interested in this thread : https://www.spigotmc.org/threads/disabling-cobblestone-and-stone.83269/

**Comment by NopeProsOnly** [comment]
Hmm. So, there is not event that gets triggered when cobblestone/stone is formed? Hopefully with skript? If not, could someone make a skript-reflect (That registers the event along with its syntax (event-world, event-location, event-block, past event-block)) that I could copy? Perhaps someone could help me understand.

**Comment by NopeProsOnly** [comment]
And that link you sent - How would I use this? I'm not very familiar with Java

**Comment by Matocolotoe** [comment]
We'll discuss about that on Discord.
