### ISSUE TITLE
Cant find the right item id for red sand.

### ISSUE THREAD

**Issue by Ande651j** [Matocolotoe/Skript-1.8#78]
### Skript Version

```
on block break:
	if player's tool is diamond shovel with lore "&cExplosive":
		loop blocks in radius 1.9 of event-block:
			if loop-block is sand or 0012/1 or soul sand or dirt or grass block:
				give loop-block to player			
				set {_drops::*} to drops of block with player's tool
				set loop-block to air
				give player {_drops}
			
on break:
  set {_drops::*} to drops of block with player's tool
  set block to air
  give player {_drops::*}				



Command /enchantts:
	trigger:
		give player diamond shovel with lore "&cExplosive"
```

### Bug Description

Server version: 1.8

SkUtilities v0.9.2
SkQuery v4.1.6
LeafSK v2.3.8
UnikPay v1.0.13(not really relevant because its a plugin for a specific server!)
WildSkript v1.8
SkAction v1.0
Vault v1.7.3-b131
Skellett v1.9.8
skript-reflect v2.3
The skripts loads in just fine but when I mine the problem occurs. It doesn't loop the red sand in my mine.

What is the right id for it? I've tried: minecraft:red_sand, 12:1 and red_sand. The skript only allows red sand but doesn't loop red sand. Just the normal sand..

### Expected Behavior

When anyone with the shovel with lore "&cExplosive" would break a block. Red sand aswell as original sand, soul sand, grass block and dirt would "loop block in radius 1.9 of event-block" when mined. But I cant find the right id for red sand.

### Steps to Reproduce

I copied my explosive pickaxe skript and switched pickaxe with shovel and changed the blocks that would loop when mined.

### Errors or Screenshots

```
Replace this text with your paste link or errors/screenshots/videos.
```

### Agreement

- [X] I have read the guidelines above and confirm I am following them with this report.

**Comment by Matocolotoe** [comment]
`red sand` works fine

**Comment by Ande651j** [comment]
Can I send video proof somewhere?

**Comment by Matocolotoe** [comment]
In this thread

**Comment by Ande651j** [comment]
youtube.com/channel/UCsFEDRnOIMnwOADokM_NJ4g
I've uploaded it on my yt. It was too big for me to upload it here.
